server {
    listen 80;
    server_name nsys.app.br;
    client_max_body_size 50M;

    location /api/ {
        proxy_pass http://napi.railway.internal:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /report/ {
        proxy_pass http://nreport-test.railway.internal:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://nfront.railway.internal:80;
        proxy_set_header Host $host;
    }
}
