server {
    listen ${PORT}; # O Railway injeta a porta automaticamente
    server_name nsys.app.br;

    # Encaminha requisições de /api para o serviço interno
    location /api/ {
        proxy_pass ${BACKEND};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Encaminha o restante para o frontend interno
    location / {
        proxy_pass ${FRONTEND};
        proxy_set_header Host $host;
    }
}
