server {
    listen 80;
    server_name nsys.app.br;

    # Encaminha requisições de /api para o serviço interno
    location /api/ {
        proxy_pass http://napi.railway.internal:8080/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Encaminha o restante para o frontend interno
    location / {
        proxy_pass http://nfront.railway.internal:80;
        proxy_set_header Host $host;
    }
}
